model:
  name: "gpt2"

data:
  dataset_name: "Anthropic/hh-rlhf"

  max_length: 512

  train_split: "train"
  val_split: "test"

  train_sample_size: 20
  val_sample_size: 20

training:
  batch_size: 4
  learning_rate: 1.0e-5
  num_epochs: 5

checkpoint:
  directory: "checkpoints"
  best_model_name: "best_model.pt"
  metric: "accuracy"